<a href="https://colab.research.google.com/github/nurcoz/Udemy_time_series/blob/main/starter_lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
%cd /content/drive/MyDrive/Python - Time Series Forecasting/Time Series Analysis/Time Series Analysis Practice

/content/drive/MyDrive/Python - Time Series Forecasting/Time Series Analysis/Time Series Analysis Practice

In [20]:
# Load Pandas
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.seasonal import seasonal_decompose

# Lab 1 - Data Loading & Index Prep

* Load the department-sales.csv dataset into a DataFrame

* Convert the date index to yyyy-mm-dd format

* Set the index frequency to weekly (W-FRI)

In [21]:
data = pd.read_csv('department-sales.csv', index_col = 0, parse_dates = True)
data.head()

            Weekly_Sales  IsHoliday
Date
05/02/2010      24924.50      False
12/02/2010      46039.49       True
19/02/2010      41595.55      False
26/02/2010      19403.54      False
05/03/2010      21827.90      False

In [22]:
# Convert the date index to yyyy-mm-dd
data.index = pd.to_datetime(data.index, format = "%d/%m/%Y")
data.index

DatetimeIndex(['2010-02-05', '2010-02-12', '2010-02-19', '2010-02-26',
               '2010-03-05', '2010-03-12', '2010-03-19', '2010-03-26',
               '2010-04-02', '2010-04-09',
               ...
               '2012-08-24', '2012-08-31', '2012-09-07', '2012-09-14',
               '2012-09-21', '2012-09-28', '2012-10-05', '2012-10-12',
               '2012-10-19', '2012-10-26'],
              dtype='datetime64[ns]', name='Date', length=143, freq=None)

In [23]:
data.head()

            Weekly_Sales  IsHoliday
Date
2010-02-05      24924.50      False
2010-02-12      46039.49       True
2010-02-19      41595.55      False
2010-02-26      19403.54      False
2010-03-05      21827.90      False

In [28]:
# Set the index frequency to weekly (W-FRI) -> freq=None to -> freq=weakly yapma

data.index.freq = "W-FRI"
data.index

DatetimeIndex(['2010-02-05', '2010-02-12', '2010-02-19', '2010-02-26',
               '2010-03-05', '2010-03-12', '2010-03-19', '2010-03-26',
               '2010-04-02', '2010-04-09',
               ...
               '2012-08-24', '2012-08-31', '2012-09-07', '2012-09-14',
               '2012-09-21', '2012-09-28', '2012-10-05', '2012-10-12',
               '2012-10-19', '2012-10-26'],
              dtype='datetime64[ns]', name='Date', length=143, freq='W-FRI')